version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ultramegasecret
      - POSTGRES_DB=neobank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - DB_SOURCE=postgresql://root:ultramegasecret@postgres:5432/neobank?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      - "/app/wait-for.sh"
      - "postgres:5432"
      - "--"
      - "/app/start.sh"
    command: [ "/app/main" ]
